### ISSUE TITLE
Where is the test? How could I use this project

### ISSUE THREAD

**Issue by stonexing** [quassum/svg-to-swiftui-core#10]
Can not install yarn on macOS 12.0
https://github.com/quassum/SVG-to-SwiftUI
Downgrade to macOS 11.6.1 and Xcode 12.5
Run SVG-to-SwiftUI I get and url "http://localhost:5000"
When I visit this http service nothing appear.
How can I use this project on macOS 12.0.1 ?

**Comment by bring-shrubbery** [comment]
Hey, you actually don't need to run this tool directly to use it. I've created a web-app that you can use to convert SVGs. You can find it here: https://github.com/quassum/SVG-to-SwiftUI

If you still want to run the tool locally you will need to install Node.js first, which as I understand you don't have installed yet (since it's not installed with Xcode command line tools).

**Comment by stonexing** [comment]
Thank you very much.
I run success after install Node.js.
Even this project support parts of SVG to SwiftUI, It still a great project.

**Comment by bring-shrubbery** [comment]
Yeah, it's definitely not complete. I do need to add support for more SVG features. Unfortunately, some features like animation are not 1-to-1 mapping between SVG and SwiftUI, so I do need to spend some time on this project in order for it to be a proper, reliable tool. I will try to find more time after my full-time job, but can't promise anything 😅
